function cheese() {
  const reverseText = document.querySelector('#reverse-text');
  const goToGen = document.querySelector('#gen-link');
  const goToDet = document.querySelector('#det-link');
  const goToFAQ = document.querySelector('#faq-link');

  reverseText.addEventListener('click', function() {
    if(document.body.classList.contains('reverse-text')) {
      document.body.classList.remove('reverse-text');
      reverseText.setAttribute('aria-pressed', 'false');
      console.log('Text Normal');
    }
    else {
      document.body.classList.add('reverse-text');
      reverseText.setAttribute('aria-pressed', 'true');
      console.log('Text Reversed');
    }
  });
  goToGen.addEventListener('click', function() {
    document.documentElement.innerHTML = `
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta charset="UTF-8">
        <title>General Info | The Annual Omniversial Demonstration of Scientific and Mystic Innovation</title>
        <link rel="stylesheet" href="Style.css">
      </head>
      <body>
        <header>
          <img src="Media - False Insanity Incorporated Logo.png" alt="A planet surrounded by rings in a spacy background with the words Insanity Incorporated">
          <cite><strong>Image generated by AI</strong></cite>
          <button id="reverse-text" aria-pressed="false">Toggle Accessible Reading Mode</button>
        </header>
        <main>
          <h1>Welcome to The Annual Omniversial Demonstration and Competition of Scientific and Mystic Innovation (AODCSMI):</h1>
          <p class="para1"><em>It has come time for the AODCSMI to begin once again!</em> During this annual event, participants from all territories of reality are welcome to share their knowledge for the betterment of all the worlds. Any who wish to observe the proceedings can sign up to attend virtually via holodeck, or pay a small fee to attend physically [transportation not provided].</p>
        </main>
        <footer>
          <button id="gen-link" style="display: none;">Hidden.ReturnSelf</button>
          <button id="det-link">Click Here for More Details</button>
          <button id="faq-link">Frequently Asked Questions</button>
          <button id="join-link">Join Us</button>
          <a href="https://asignin.space/">Read a Message From Our Sponsers</a>
          <p class="footer">Hosted by Insanity Incorporated; Funded by Interdimensional Enterprises plus donations</p>
        </footer>
        <script src="Script.js"></script>
      </body>
    `;
    console.log('Go To Gen');
    cheese();
  });
  goToDet.addEventListener('click', function() {
    document.documentElement.innerHTML = `
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta charset="UTF-8">
        <title>Details | The Annual Omniversial Demonstration of Scientific and Mystic Innovation</Title>
        <link rel="stylesheet" href="Style.css">
      </head>
      <body>
        <header>
          <img src="Media - False Insanity Incorporated Logo.png" alt="A planet surrounded by rings in a spacy background with the words Insanity Incorporated">
          <cite><strong>Image generated by AI</strong></cite>
          <button id="reverse-text" aria-pressed="false">Toggle Accessible Reading Mode</button>
        </header>
        <main class="main-flex-container">
          <section>
            <h1>Here is some more information about The Anuel Omniversial Demonstration and Competition of Scientific and Mystic Innovation (AODCSMI):</h1>
          </section>
          <section>
            <h2>Time and location:</h2>
            <h3>Date:</h3>
            <p>7W2,035,122,539,100,247,677.000</p>
            <h3>Location:</h3>
            <p>Void Station; Prime territory; 0.91252 - 0.34 - 0.0.99999999999999999996 - 3i/uNt/RR28/881.11.1</p>
          </section>
          <section>
            <h2>Station Map</h2>
            <p>Below is a map of the void station in which this event will take place.</p>
            <img src="Media - Station Map.png" alt="A map depicting a complex network of labeled passages and rooms">
            <cite><strong>Image generated by AI</strong></cite>
          </section>
          <section>
            <h2><strong>Disclaimer:</strong></h2>
            <p><em>Keep in mind: This event may or may not exist!</em>
              <br>
            We refuse to confirm or deny the existence of the AODCSMI. However, we do guarantee that this event, whether it is real or fictitious, was made with no malicious intent, and no harm will befall you or your eternal soul if you decide to join it. This we solemnly swear in the name of Edword.</p>
          </section>
          <section>
            <p class="iblar-text">Zh/q/chiiI/1. De/arrdw/maa.xhh</p>
          </section>
        </main>
        <footer>
          <button id="gen-link">Back to General Info</button>
          <button id="det-link" style="display: none;">Hidden.ReturnSelf</button>
          <button id="faq-link">Frequently Asked Questions</button>
          <button id="join-link">Join Us</button>
          <a href="https://asignin.space/">Read a message from our sponsors</a>
          <p class="footer">Hosted by Insanity Incorporated; Funded by Interdimensional Enterprises plus donations</p>
        </footer>
        <script src="Script.js"></script>
      </body>
    `;
    console.log('Go To Details');
    cheese();
  });
  goToFAQ.addEventListener('click', function() {
    document.documentElement.innerHTML = `
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta charset="UTF-8">
        <title>FAQ | The Annual Omniversial Demonstration of Scientific and Mystic Innovation</title>
        <link rel="stylesheet" href="Style.css">
      </head>
      <body>
        <header>
          <img src="Media - False Insanity Incorporated Logo.png" alt="A planet surrounded by rings in a spacy background with the words Insanity Incorporated">
          <cite><strong>Image generated by AI</strong></cite>
          <button id="reverse-text" aria-pressed="false">Toggle Accessible Reading Mode</button>
        </header>
        <main class="main-flex-container">
          <section>
            <h1>Frequently Asked Questions:</h1>
            <p>Here are some of the frequently asked questions beings from across existence have inquired about in regards to this conference.</p>
          </section>
          <section>
            <button id="question-1" aria-expanded="false" aria-controls="answer-1">Question: How long is this event?</button>
            <div id="answer-1" class="default-grid-container" aria-hidden="true">
              <div class="grid-inner">
                <p>Answer: The length of The Annual Omniversial Demonstration and Competition of Scientific and Mystic Innovation is not determined at this time, as not all presenters have submitted the innovation they plan to demonstrate. The average length of prier iterations of The Annual Omniversial Demonstration and Competition of Scientific and Mystic Innovation is W0.00093. Please keep in mind that audience members are not required to stay for the entirety of the event, and presenters are only required to appear during the time in which they are scheduled to present their innovation.</p>
              </div>
            </div>
          </section>
          <section>
            <button id="question-2" aria-expanded="false" aria-controls="answer-2">Question: Are audience members and presenters allowed to sleep at the station?</button>
            <div id="answer-2" class="default-grid-container" aria-hidden="true">
              <div class="grid-inner">
                <p>Answer: Yes, sleeping is not banned in the facility in which the Annual Omniversial demonstration of Scientific and Mystic Innovation is held. However, due to the variety of beings attending this event, sleeping infrastructure, such as bedding, is not provided. If such infrastructure is necessary for either an in-person audience member or presenter to attend our event, they may either bring it with them or choose to not attend the event physically.</p>
              </div>
            </div>
          </section>
          <section>
            <button id="question-3" aria-expanded="false" aria-controls="answer-3">Question: What's up with the eyeballs watching me from the walls?</button>
            <div id="answer-3" class="default-grid-container" aria-hidden="true">
              <div class="grid-inner">
                <p>Answer: Many of our audience members and presenters have reported black eyes watching them from the walls, usually while they are attempting to enter sleep. The answer to this question is not currently available, and we ask that our customers do not inquire further.</p>
              </div>
            </div>
          </section>
        </main>
        <footer>
          <button id="gen-link">Back to General Info</button>
          <button id="det-link">Back to Details</button>
          <button id="faq-link" style="display: none;">Hidden.ReturnSelf</button>
          <button id="join-link">Join Us</button>
          <a href="https://asignin.space/">Read a Message From Our Sponsors</a>
          <p class="footer">Hosted by Insanity Incorporated; Funded by Interdimensional Enterprises plus donations</p>
        </footer>
        <script src="Script.js"></script>
      </body>
    `;
    console.log('Go To FAQ');
    cheese();
    const question1 = document.querySelector('#question-1');
    const answer1 = document.querySelector('#answer-1');
    const question2 = document.querySelector('#question-2');
    const answer2 = document.querySelector('#answer-2');
    const question3 = document.querySelector('#question-3');
    const answer3 = document.querySelector('#answer-3');

    function toggleVisibility(qElement, aElement) {
      if(aElement.classList.contains('open-grid-container')) {
        aElement.classList.remove('open-grid-container');
        qElement.setAttribute('aria-expanded', 'false');
        aElement.setAttribute('aria-hidden', 'true');
        console.log('Answer Hidden');
      }
      else {
        aElement.classList.add('open-grid-container');
        qElement.setAttribute('aria-expanded', 'true');
        aElement.setAttribute('aria-hidden', 'false');
        console.log('Answer Shown');
      }
    }

    question1.addEventListener('click', function() {
      toggleVisibility(question1, answer1)
    });
    question2.addEventListener('click', function() {
      toggleVisibility(question2, answer2)
    });
    question3.addEventListener('click', function() {
      toggleVisibility(question3, answer3)
    });
  });
}
cheese();
